services:
  nlp-model:
    build: .
    container_name: nlp-sentiment-model
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - n8n_default

networks:
  n8n_default:
    external: true
